### ISSUE TITLE
Add option for self-signed certs (TLS/SSL)

### ISSUE THREAD

**Issue by ghost** [symfony/swiftmailer-bundle#134]
I like to use encryption (SSL/TLS) with **self-signed certificates**. For this it would be nice to add an easy option to support this.

**Comment by EternallLight** [comment]
I've faced the same issues and agree.

**Comment by uvups** [comment]
Yes, please. 👍

**Comment by ox160d05d** [comment]
I completly agree with the author.

**Comment by fabpot** [comment]
Anyone willing to make a pull request to add this feature?

**Comment by ox160d05d** [comment]
fabpot, how about this?
https://github.com/symfony/swiftmailer-bundle/pull/141

**Comment by Adambean** [comment]
At the very least could we be able to accept CA's in the system's trusted CA store?

I ask this because our company web servers (6 of them) use WHM with certificates signed by our own CA. This isn't quite as ideal as expensively getting a common trusted CA for each server, but it's one step better than self-signed due to there being some form of signature chain in place.
