### ISSUE TITLE
non-existent service "router.request_context" in v2.5.0

### ISSUE THREAD

**Issue by quantumpacket** [symfony/swiftmailer-bundle#163]
I have a basic CLI app and just updated this bundle to 2.5.x and now I am getting the following error message presumably from this commit https://github.com/symfony/swiftmailer-bundle/commit/183b2916a74c708301e593c42d8d406d226ee8f2. This seems similar to this [issue](https://github.com/symfony/symfony/issues/11466). I don't need a router in my CLI app so I have removed it from my config, but switmailer-bundle is depending on it.

> [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]   
  The service "swiftmailer.mailer.default.transport.dynamic" has a dependency  
   on a non-existent service "router.request_context".

**Comment by fabpot** [comment]
ping @HeahDude

**Comment by stof** [comment]
we should add ``on-invalid=null`` for the reference, as the request_context is used only for the SMTP configurator, and it is optional there.

However, this issue should be triggered only when using a dynamic configuration for the transport, which is weird if you just updated the bundle (as such config was forbidden with the previous version). Otherwise, it means that the new code is buggy and always uses dynamic mode.

**Comment by HeahDude** [comment]
Should I mention that @stof is right? See #166.

**Comment by HeahDude** [comment]
@stof about
>Otherwise, it means that the new code is buggy and always uses dynamic mode.

This is conditioned by https://github.com/symfony/swiftmailer-bundle/pull/161/files#diff-5d7bc2844ac399afc20f4d92a4897c2cR75, should be safe right?
