### ISSUE TITLE
Custom sendmail command is not being processed if there are no link to .env file

### ISSUE THREAD

**Issue by ArchieDoe** [symfony/swiftmailer-bundle#244]
In `config/packages/swiftmailer.yaml` next config

```
swiftmailer:
    transport: 'sendmail'
    command: '/usr/bin/msmtp -t -i'
```

will not be interpreted properly: `command` property will be omitted.

This happens because of next code:

```
if ($usedEnvs && !$disableDelivery) {
    // Factory sets here.
}
```

In case of configuration above `$usedEnvs` is always empty, which requires to store some information in `.env` file.

**Comment by kojiDev** [comment]
I agree that condition is rather odd.
The whole `SwiftmailerExtension` and `SwiftmailerTransportFactory` are quite difficult to understand. At one point we are checking that that there's no env vars and configuring transport using a factory, otherwise we use `configureMailerTransport` method, which seemingly does the same.

**Comment by Toflar** [comment]
I just had the same issue and imho it's not even related to environment vars. The command is just ignored completely. You may check my PR (https://github.com/symfony/swiftmailer-bundle/pull/286) and provide feedback if that fixes it for you.
