### ISSUE TITLE
On the data collector, check if the body is a string before base64 encoding it

### ISSUE THREAD

**Issue by Taluu** [symfony/swiftmailer-bundle#249]
We are currently using mailjet's templates to send our emails, but we have an error saying that the array cannot be converted to string on the base64_encode call in the DataCollector.

Checking if it's a string and if it's one (or checking if base64 is supported ?) would be a way to go ?

**Comment by lyrixx** [comment]
Yes, I think so. Would you mind create a PR?
Thanks

**Comment by stof** [comment]
`Swift_Message::getBody` (actually inherited from `Swift_Mime_SimpleMimeEntity::getBody`) is documented as `@return string`. So I don't think that the bundle should cover the case of this property being an array. If you extend a class and breaks its contract, the bug is in the child class, not in the consuming code.
