### ISSUE TITLE
Logger log doubles

### ISSUE THREAD

**Issue by Nek-** [symfony/swiftmailer-bundle#69]
Hello,

I'm making some symfony commands witch send mails and test them.

The process in command is the following (see the symfony documentation here: http://symfony.com/doc/current/cookbook/console/sending_emails.html ):

``` php
$mailer = $container->get('mailer');

// Log each message "sent"
$mailer->send($message);

// now manually flush the queue
$spool = $mailer->getTransport()->getSpool();
$transport = $container->get('swiftmailer.transport.real');

// Re-log the message
$spool->flushQueue($transport);
```

The result of this operation is obvious, if you send 2 messages, the logger will tell you that you sent 4.

Is it a willing feature or a real bug ? Because it's really weird.

**Comment by TrickyC94** [comment]
I've just noticed this behaviour too (v2.6.7). I tried to reproduce what happened under the hood. 

1. I call `$mailer->send($message)`
2. The mailer calls `$this->_transport->send($message)` where _transport is a SpoolTransport instance
3. The SpoolTransport dispatches the **"beforeSendPerformed"** event
4. Logger is subscribed to that event and log **once**
5. Symfony dispatches the **"kernel.terminate"** event
6. The EmailSenderListner is subscribed to that event and it calls `$spool->flushQueue($realTransport)` in my case $spool is MemorySpool and the real transport now is the NullTransport
7. The flushQueue method calls the send method on NullTransport
8. NullTransport dispatches the **"beforeSendPerformed"**
9. Logger is subscribed to that event and logs **twice**

I think that this behaviour needs to be reviewed somehow, or, if this is the expected behaviour, to update the docs

**Comment by fabpot** [comment]
Closing old issues.
